my.greeting: hello

app.description: "${app.name:defaultValue}"

my.lists: "${example.password}"
server.port: 8080
number: 5
db.values: "{connection.string:'http//', username:'foo', password:'pass'}"

management.endpoints.web.exposure.include: "*"

spring.profiles.active: test

spring.cloud.config.uri: http://localhost:8888/
